export default [
  'American Sign Language', 
  'العربية - Arabic', 
  'বাংলা - Bengali', 
  '粤语 - Cantonese', 
  'Français - French', 
  'Deutsch - German', 
  'עִבְרִית - Hebrew', 
  'हिन्दी - Hindi', 
  'Italiano - Italian', 
  '日本語 - Japanese', 
  'Jawa - Javanese', 
  '한국어 - Korean', 
  '普通话 - Mandarin', 
  'मराठी - Marathi', 
  'Polski - Polish', 
  'Português - Portuguese', 
  'ਪੰਜਾਬੀ - Punjabi', 
  'Русский - Russian', 
  'Español - Spanish', 
  'Tagalog - Tagalog', 
  'தமிழ் - Tamil', 
  'Türkçe - Turkish', 
  'Tiếng Việt - Vietnamese', 
  '吴语 - Wu',
]
